import ScrollObserver from '@/hooks/use-scroll-observer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Cursor from '@/components/Cursor'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cursor/>
        <ScrollObserver>
        {children}
        </ScrollObserver>
      </body>
    </html>
  )
}
