import ScrollObserver from "@/hooks/use-scroll-observer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Cursor from "@/components/Cursor";
import Script from "next/script";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        <Navbar />
        <Cursor />
        <ScrollObserver>{children}</ScrollObserver>
      </body>
    </html>
  );
}
